#!/bin/bash
# Auto-generated PDB/AlphaFold download script
# Generated 2026-03-02 02:14

set -e

# 90 PDB structures + 27 AlphaFold models

mkdir -p structures/pdb structures/alphafold

echo '=== Downloading PDB crystal structures ==='
[ -f structures/pdb/193L.cif ] || wget -q -O structures/pdb/193L.cif "https://files.rcsb.org/download/193L.cif" && echo "  193L: OK" || echo "  193L: FAILED"
[ -f structures/pdb/1AKE.cif ] || wget -q -O structures/pdb/1AKE.cif "https://files.rcsb.org/download/1AKE.cif" && echo "  1AKE: OK" || echo "  1AKE: FAILED"
[ -f structures/pdb/1AKI.cif ] || wget -q -O structures/pdb/1AKI.cif "https://files.rcsb.org/download/1AKI.cif" && echo "  1AKI: OK" || echo "  1AKI: FAILED"
[ -f structures/pdb/1AP4.cif ] || wget -q -O structures/pdb/1AP4.cif "https://files.rcsb.org/download/1AP4.cif" && echo "  1AP4: OK" || echo "  1AP4: FAILED"
[ -f structures/pdb/1ATP.cif ] || wget -q -O structures/pdb/1ATP.cif "https://files.rcsb.org/download/1ATP.cif" && echo "  1ATP: OK" || echo "  1ATP: FAILED"
[ -f structures/pdb/1BG2.cif ] || wget -q -O structures/pdb/1BG2.cif "https://files.rcsb.org/download/1BG2.cif" && echo "  1BG2: OK" || echo "  1BG2: FAILED"
[ -f structures/pdb/1BIN.cif ] || wget -q -O structures/pdb/1BIN.cif "https://files.rcsb.org/download/1BIN.cif" && echo "  1BIN: OK" || echo "  1BIN: FAILED"
[ -f structures/pdb/1BMF.cif ] || wget -q -O structures/pdb/1BMF.cif "https://files.rcsb.org/download/1BMF.cif" && echo "  1BMF: OK" || echo "  1BMF: FAILED"
[ -f structures/pdb/1BZP.cif ] || wget -q -O structures/pdb/1BZP.cif "https://files.rcsb.org/download/1BZP.cif" && echo "  1BZP: OK" || echo "  1BZP: FAILED"
[ -f structures/pdb/1BZR.cif ] || wget -q -O structures/pdb/1BZR.cif "https://files.rcsb.org/download/1BZR.cif" && echo "  1BZR: OK" || echo "  1BZR: FAILED"
[ -f structures/pdb/1CDK.cif ] || wget -q -O structures/pdb/1CDK.cif "https://files.rcsb.org/download/1CDK.cif" && echo "  1CDK: OK" || echo "  1CDK: FAILED"
[ -f structures/pdb/1CFD.cif ] || wget -q -O structures/pdb/1CFD.cif "https://files.rcsb.org/download/1CFD.cif" && echo "  1CFD: OK" || echo "  1CFD: FAILED"
[ -f structures/pdb/1CK7.cif ] || wget -q -O structures/pdb/1CK7.cif "https://files.rcsb.org/download/1CK7.cif" && echo "  1CK7: OK" || echo "  1CK7: FAILED"
[ -f structures/pdb/1CLL.cif ] || wget -q -O structures/pdb/1CLL.cif "https://files.rcsb.org/download/1CLL.cif" && echo "  1CLL: OK" || echo "  1CLL: FAILED"
[ -f structures/pdb/1D8U.cif ] || wget -q -O structures/pdb/1D8U.cif "https://files.rcsb.org/download/1D8U.cif" && echo "  1D8U: OK" || echo "  1D8U: FAILED"
[ -f structures/pdb/1DLY.cif ] || wget -q -O structures/pdb/1DLY.cif "https://files.rcsb.org/download/1DLY.cif" && echo "  1DLY: OK" || echo "  1DLY: FAILED"
[ -f structures/pdb/1EA5.cif ] || wget -q -O structures/pdb/1EA5.cif "https://files.rcsb.org/download/1EA5.cif" && echo "  1EA5: OK" || echo "  1EA5: FAILED"
[ -f structures/pdb/1ERK.cif ] || wget -q -O structures/pdb/1ERK.cif "https://files.rcsb.org/download/1ERK.cif" && echo "  1ERK: OK" || echo "  1ERK: FAILED"
[ -f structures/pdb/1EVE.cif ] || wget -q -O structures/pdb/1EVE.cif "https://files.rcsb.org/download/1EVE.cif" && echo "  1EVE: OK" || echo "  1EVE: FAILED"
[ -f structures/pdb/1F54.cif ] || wget -q -O structures/pdb/1F54.cif "https://files.rcsb.org/download/1F54.cif" && echo "  1F54: OK" || echo "  1F54: FAILED"
[ -f structures/pdb/1F55.cif ] || wget -q -O structures/pdb/1F55.cif "https://files.rcsb.org/download/1F55.cif" && echo "  1F55: OK" || echo "  1F55: FAILED"
[ -f structures/pdb/1FDH.cif ] || wget -q -O structures/pdb/1FDH.cif "https://files.rcsb.org/download/1FDH.cif" && echo "  1FDH: OK" || echo "  1FDH: FAILED"
[ -f structures/pdb/1FMV.cif ] || wget -q -O structures/pdb/1FMV.cif "https://files.rcsb.org/download/1FMV.cif" && echo "  1FMV: OK" || echo "  1FMV: FAILED"
[ -f structures/pdb/1FSX.cif ] || wget -q -O structures/pdb/1FSX.cif "https://files.rcsb.org/download/1FSX.cif" && echo "  1FSX: OK" || echo "  1FSX: FAILED"
[ -f structures/pdb/1FTJ.cif ] || wget -q -O structures/pdb/1FTJ.cif "https://files.rcsb.org/download/1FTJ.cif" && echo "  1FTJ: OK" || echo "  1FTJ: FAILED"
[ -f structures/pdb/1FTK.cif ] || wget -q -O structures/pdb/1FTK.cif "https://files.rcsb.org/download/1FTK.cif" && echo "  1FTK: OK" || echo "  1FTK: FAILED"
[ -f structures/pdb/1G09.cif ] || wget -q -O structures/pdb/1G09.cif "https://files.rcsb.org/download/1G09.cif" && echo "  1G09: OK" || echo "  1G09: FAILED"
[ -f structures/pdb/1GD6.cif ] || wget -q -O structures/pdb/1GD6.cif "https://files.rcsb.org/download/1GD6.cif" && echo "  1GD6: OK" || echo "  1GD6: FAILED"
[ -f structures/pdb/1GDI.cif ] || wget -q -O structures/pdb/1GDI.cif "https://files.rcsb.org/download/1GDI.cif" && echo "  1GDI: OK" || echo "  1GDI: FAILED"
[ -f structures/pdb/1HCK.cif ] || wget -q -O structures/pdb/1HCK.cif "https://files.rcsb.org/download/1HCK.cif" && echo "  1HCK: OK" || echo "  1HCK: FAILED"
[ -f structures/pdb/1HEL.cif ] || wget -q -O structures/pdb/1HEL.cif "https://files.rcsb.org/download/1HEL.cif" && echo "  1HEL: OK" || echo "  1HEL: FAILED"
[ -f structures/pdb/1HHO.cif ] || wget -q -O structures/pdb/1HHO.cif "https://files.rcsb.org/download/1HHO.cif" && echo "  1HHO: OK" || echo "  1HHO: FAILED"
[ -f structures/pdb/1HHP.cif ] || wget -q -O structures/pdb/1HHP.cif "https://files.rcsb.org/download/1HHP.cif" && echo "  1HHP: OK" || echo "  1HHP: FAILED"
[ -f structures/pdb/1HSG.cif ] || wget -q -O structures/pdb/1HSG.cif "https://files.rcsb.org/download/1HSG.cif" && echo "  1HSG: OK" || echo "  1HSG: FAILED"
[ -f structures/pdb/1IDR.cif ] || wget -q -O structures/pdb/1IDR.cif "https://files.rcsb.org/download/1IDR.cif" && echo "  1IDR: OK" || echo "  1IDR: FAILED"
[ -f structures/pdb/1IEP.cif ] || wget -q -O structures/pdb/1IEP.cif "https://files.rcsb.org/download/1IEP.cif" && echo "  1IEP: OK" || echo "  1IEP: FAILED"
[ -f structures/pdb/1IG8.cif ] || wget -q -O structures/pdb/1IG8.cif "https://files.rcsb.org/download/1IG8.cif" && echo "  1IG8: OK" || echo "  1IG8: FAILED"
[ -f structures/pdb/1IOM.cif ] || wget -q -O structures/pdb/1IOM.cif "https://files.rcsb.org/download/1IOM.cif" && echo "  1IOM: OK" || echo "  1IOM: FAILED"
[ -f structures/pdb/1IWT.cif ] || wget -q -O structures/pdb/1IWT.cif "https://files.rcsb.org/download/1IWT.cif" && echo "  1IWT: OK" || echo "  1IWT: FAILED"
[ -f structures/pdb/1IXE.cif ] || wget -q -O structures/pdb/1IXE.cif "https://files.rcsb.org/download/1IXE.cif" && echo "  1IXE: OK" || echo "  1IXE: FAILED"
[ -f structures/pdb/1JWR.cif ] || wget -q -O structures/pdb/1JWR.cif "https://files.rcsb.org/download/1JWR.cif" && echo "  1JWR: OK" || echo "  1JWR: FAILED"
[ -f structures/pdb/1LYZ.cif ] || wget -q -O structures/pdb/1LYZ.cif "https://files.rcsb.org/download/1LYZ.cif" && echo "  1LYZ: OK" || echo "  1LYZ: FAILED"
[ -f structures/pdb/1LZA.cif ] || wget -q -O structures/pdb/1LZA.cif "https://files.rcsb.org/download/1LZA.cif" && echo "  1LZA: OK" || echo "  1LZA: FAILED"
[ -f structures/pdb/1MBD.cif ] || wget -q -O structures/pdb/1MBD.cif "https://files.rcsb.org/download/1MBD.cif" && echo "  1MBD: OK" || echo "  1MBD: FAILED"
[ -f structures/pdb/1MOH.cif ] || wget -q -O structures/pdb/1MOH.cif "https://files.rcsb.org/download/1MOH.cif" && echo "  1MOH: OK" || echo "  1MOH: FAILED"
[ -f structures/pdb/1MUO.cif ] || wget -q -O structures/pdb/1MUO.cif "https://files.rcsb.org/download/1MUO.cif" && echo "  1MUO: OK" || echo "  1MUO: FAILED"
[ -f structures/pdb/1NME.cif ] || wget -q -O structures/pdb/1NME.cif "https://files.rcsb.org/download/1NME.cif" && echo "  1NME: OK" || echo "  1NME: FAILED"
[ -f structures/pdb/1P0I.cif ] || wget -q -O structures/pdb/1P0I.cif "https://files.rcsb.org/download/1P0I.cif" && echo "  1P0I: OK" || echo "  1P0I: FAILED"
[ -f structures/pdb/1P0M.cif ] || wget -q -O structures/pdb/1P0M.cif "https://files.rcsb.org/download/1P0M.cif" && echo "  1P0M: OK" || echo "  1P0M: FAILED"
[ -f structures/pdb/1P38.cif ] || wget -q -O structures/pdb/1P38.cif "https://files.rcsb.org/download/1P38.cif" && echo "  1P38: OK" || echo "  1P38: FAILED"
[ -f structures/pdb/1PAU.cif ] || wget -q -O structures/pdb/1PAU.cif "https://files.rcsb.org/download/1PAU.cif" && echo "  1PAU: OK" || echo "  1PAU: FAILED"
[ -f structures/pdb/1PPB.cif ] || wget -q -O structures/pdb/1PPB.cif "https://files.rcsb.org/download/1PPB.cif" && echo "  1PPB: OK" || echo "  1PPB: FAILED"
[ -f structures/pdb/1RJV.cif ] || wget -q -O structures/pdb/1RJV.cif "https://files.rcsb.org/download/1RJV.cif" && echo "  1RJV: OK" || echo "  1RJV: FAILED"
[ -f structures/pdb/1S0Q.cif ] || wget -q -O structures/pdb/1S0Q.cif "https://files.rcsb.org/download/1S0Q.cif" && echo "  1S0Q: OK" || echo "  1S0Q: FAILED"
[ -f structures/pdb/1SPY.cif ] || wget -q -O structures/pdb/1SPY.cif "https://files.rcsb.org/download/1SPY.cif" && echo "  1SPY: OK" || echo "  1SPY: FAILED"
[ -f structures/pdb/1UDT.cif ] || wget -q -O structures/pdb/1UDT.cif "https://files.rcsb.org/download/1UDT.cif" && echo "  1UDT: OK" || echo "  1UDT: FAILED"
[ -f structures/pdb/1UTN.cif ] || wget -q -O structures/pdb/1UTN.cif "https://files.rcsb.org/download/1UTN.cif" && echo "  1UTN: OK" || echo "  1UTN: FAILED"
[ -f structures/pdb/1V4S.cif ] || wget -q -O structures/pdb/1V4S.cif "https://files.rcsb.org/download/1V4S.cif" && echo "  1V4S: OK" || echo "  1V4S: FAILED"
[ -f structures/pdb/1V4T.cif ] || wget -q -O structures/pdb/1V4T.cif "https://files.rcsb.org/download/1V4T.cif" && echo "  1V4T: OK" || echo "  1V4T: FAILED"
[ -f structures/pdb/1VOM.cif ] || wget -q -O structures/pdb/1VOM.cif "https://files.rcsb.org/download/1VOM.cif" && echo "  1VOM: OK" || echo "  1VOM: FAILED"
[ -f structures/pdb/1W7J.cif ] || wget -q -O structures/pdb/1W7J.cif "https://files.rcsb.org/download/1W7J.cif" && echo "  1W7J: OK" || echo "  1W7J: FAILED"
[ -f structures/pdb/1W8J.cif ] || wget -q -O structures/pdb/1W8J.cif "https://files.rcsb.org/download/1W8J.cif" && echo "  1W8J: OK" || echo "  1W8J: FAILED"
[ -f structures/pdb/1XCK.cif ] || wget -q -O structures/pdb/1XCK.cif "https://files.rcsb.org/download/1XCK.cif" && echo "  1XCK: OK" || echo "  1XCK: FAILED"
[ -f structures/pdb/1Y57.cif ] || wget -q -O structures/pdb/1Y57.cif "https://files.rcsb.org/download/1Y57.cif" && echo "  1Y57: OK" || echo "  1Y57: FAILED"
[ -f structures/pdb/1Z83.cif ] || wget -q -O structures/pdb/1Z83.cif "https://files.rcsb.org/download/1Z83.cif" && echo "  1Z83: OK" || echo "  1Z83: FAILED"
[ -f structures/pdb/1ZIN.cif ] || wget -q -O structures/pdb/1ZIN.cif "https://files.rcsb.org/download/1ZIN.cif" && echo "  1ZIN: OK" || echo "  1ZIN: FAILED"
[ -f structures/pdb/1ZIO.cif ] || wget -q -O structures/pdb/1ZIO.cif "https://files.rcsb.org/download/1ZIO.cif" && echo "  1ZIO: OK" || echo "  1ZIO: FAILED"
[ -f structures/pdb/2BCX.cif ] || wget -q -O structures/pdb/2BCX.cif "https://files.rcsb.org/download/2BCX.cif" && echo "  2BCX: OK" || echo "  2BCX: FAILED"
[ -f structures/pdb/2C95.cif ] || wget -q -O structures/pdb/2C95.cif "https://files.rcsb.org/download/2C95.cif" && echo "  2C95: OK" || echo "  2C95: FAILED"
[ -f structures/pdb/2CTS.cif ] || wget -q -O structures/pdb/2CTS.cif "https://files.rcsb.org/download/2CTS.cif" && echo "  2CTS: OK" || echo "  2CTS: FAILED"
[ -f structures/pdb/2DN1.cif ] || wget -q -O structures/pdb/2DN1.cif "https://files.rcsb.org/download/2DN1.cif" && echo "  2DN1: OK" || echo "  2DN1: FAILED"
[ -f structures/pdb/2DN2.cif ] || wget -q -O structures/pdb/2DN2.cif "https://files.rcsb.org/download/2DN2.cif" && echo "  2DN2: OK" || echo "  2DN2: FAILED"
[ -f structures/pdb/2ERK.cif ] || wget -q -O structures/pdb/2ERK.cif "https://files.rcsb.org/download/2ERK.cif" && echo "  2ERK: OK" || echo "  2ERK: FAILED"
[ -f structures/pdb/2HHB.cif ] || wget -q -O structures/pdb/2HHB.cif "https://files.rcsb.org/download/2HHB.cif" && echo "  2HHB: OK" || echo "  2HHB: FAILED"
[ -f structures/pdb/2HYY.cif ] || wget -q -O structures/pdb/2HYY.cif "https://files.rcsb.org/download/2HYY.cif" && echo "  2HYY: OK" || echo "  2HYY: FAILED"
[ -f structures/pdb/2J4Z.cif ] || wget -q -O structures/pdb/2J4Z.cif "https://files.rcsb.org/download/2J4Z.cif" && echo "  2J4Z: OK" || echo "  2J4Z: FAILED"
[ -f structures/pdb/2LHB.cif ] || wget -q -O structures/pdb/2LHB.cif "https://files.rcsb.org/download/2LHB.cif" && echo "  2LHB: OK" || echo "  2LHB: FAILED"
[ -f structures/pdb/2LZM.cif ] || wget -q -O structures/pdb/2LZM.cif "https://files.rcsb.org/download/2LZM.cif" && echo "  2LZM: OK" || echo "  2LZM: FAILED"
[ -f structures/pdb/2SRC.cif ] || wget -q -O structures/pdb/2SRC.cif "https://files.rcsb.org/download/2SRC.cif" && echo "  2SRC: OK" || echo "  2SRC: FAILED"
[ -f structures/pdb/2YHX.cif ] || wget -q -O structures/pdb/2YHX.cif "https://files.rcsb.org/download/2YHX.cif" && echo "  2YHX: OK" || echo "  2YHX: FAILED"
[ -f structures/pdb/3CLN.cif ] || wget -q -O structures/pdb/3CLN.cif "https://files.rcsb.org/download/3CLN.cif" && echo "  3CLN: OK" || echo "  3CLN: FAILED"
[ -f structures/pdb/3GI3.cif ] || wget -q -O structures/pdb/3GI3.cif "https://files.rcsb.org/download/3GI3.cif" && echo "  3GI3: OK" || echo "  3GI3: FAILED"
[ -f structures/pdb/3KIN.cif ] || wget -q -O structures/pdb/3KIN.cif "https://files.rcsb.org/download/3KIN.cif" && echo "  3KIN: OK" || echo "  3KIN: FAILED"
[ -f structures/pdb/4AKE.cif ] || wget -q -O structures/pdb/4AKE.cif "https://files.rcsb.org/download/4AKE.cif" && echo "  4AKE: OK" || echo "  4AKE: FAILED"
[ -f structures/pdb/4CTS.cif ] || wget -q -O structures/pdb/4CTS.cif "https://files.rcsb.org/download/4CTS.cif" && echo "  4CTS: OK" || echo "  4CTS: FAILED"
[ -f structures/pdb/4EY4.cif ] || wget -q -O structures/pdb/4EY4.cif "https://files.rcsb.org/download/4EY4.cif" && echo "  4EY4: OK" || echo "  4EY4: FAILED"
[ -f structures/pdb/4EY7.cif ] || wget -q -O structures/pdb/4EY7.cif "https://files.rcsb.org/download/4EY7.cif" && echo "  4EY7: OK" || echo "  4EY7: FAILED"
[ -f structures/pdb/4HHB.cif ] || wget -q -O structures/pdb/4HHB.cif "https://files.rcsb.org/download/4HHB.cif" && echo "  4HHB: OK" || echo "  4HHB: FAILED"
[ -f structures/pdb/4PEP.cif ] || wget -q -O structures/pdb/4PEP.cif "https://files.rcsb.org/download/4PEP.cif" && echo "  4PEP: OK" || echo "  4PEP: FAILED"
[ -f structures/pdb/6LYZ.cif ] || wget -q -O structures/pdb/6LYZ.cif "https://files.rcsb.org/download/6LYZ.cif" && echo "  6LYZ: OK" || echo "  6LYZ: FAILED"

echo '=== Downloading AlphaFold models ==='
[ -f structures/alphafold/AF-P00519-F1-model_v4.cif ] || wget -q -O structures/alphafold/AF-P00519-F1-model_v4.cif "https://alphafold.ebi.ac.uk/files/AF-P00519-F1-model_v4.cif" && echo "  AF-P00519: OK" || echo "  AF-P00519: FAILED"
[ -f structures/alphafold/AF-P00698-F1-model_v4.cif ] || wget -q -O structures/alphafold/AF-P00698-F1-model_v4.cif "https://alphafold.ebi.ac.uk/files/AF-P00698-F1-model_v4.cif" && echo "  AF-P00698: OK" || echo "  AF-P00698: FAILED"
[ -f structures/alphafold/AF-P00699-F1-model_v4.cif ] || wget -q -O structures/alphafold/AF-P00699-F1-model_v4.cif "https://alphafold.ebi.ac.uk/files/AF-P00699-F1-model_v4.cif" && echo "  AF-P00699: OK" || echo "  AF-P00699: FAILED"
[ -f structures/alphafold/AF-P00703-F1-model_v4.cif ] || wget -q -O structures/alphafold/AF-P00703-F1-model_v4.cif "https://alphafold.ebi.ac.uk/files/AF-P00703-F1-model_v4.cif" && echo "  AF-P00703: OK" || echo "  AF-P00703: FAILED"
[ -f structures/alphafold/AF-P01942-F1-model_v4.cif ] || wget -q -O structures/alphafold/AF-P01942-F1-model_v4.cif "https://alphafold.ebi.ac.uk/files/AF-P01942-F1-model_v4.cif" && echo "  AF-P01942: OK" || echo "  AF-P01942: FAILED"
[ -f structures/alphafold/AF-P02062-F1-model_v4.cif ] || wget -q -O structures/alphafold/AF-P02062-F1-model_v4.cif "https://alphafold.ebi.ac.uk/files/AF-P02062-F1-model_v4.cif" && echo "  AF-P02062: OK" || echo "  AF-P02062: FAILED"
[ -f structures/alphafold/AF-P02144-F1-model_v4.cif ] || wget -q -O structures/alphafold/AF-P02144-F1-model_v4.cif "https://alphafold.ebi.ac.uk/files/AF-P02144-F1-model_v4.cif" && echo "  AF-P02144: OK" || echo "  AF-P02144: FAILED"
[ -f structures/alphafold/AF-P02185-F1-model_v4.cif ] || wget -q -O structures/alphafold/AF-P02185-F1-model_v4.cif "https://alphafold.ebi.ac.uk/files/AF-P02185-F1-model_v4.cif" && echo "  AF-P02185: OK" || echo "  AF-P02185: FAILED"
[ -f structures/alphafold/AF-P02189-F1-model_v4.cif ] || wget -q -O structures/alphafold/AF-P02189-F1-model_v4.cif "https://alphafold.ebi.ac.uk/files/AF-P02189-F1-model_v4.cif" && echo "  AF-P02189: OK" || echo "  AF-P02189: FAILED"
[ -f structures/alphafold/AF-P02585-F1-model_v4.cif ] || wget -q -O structures/alphafold/AF-P02585-F1-model_v4.cif "https://alphafold.ebi.ac.uk/files/AF-P02585-F1-model_v4.cif" && echo "  AF-P02585: OK" || echo "  AF-P02585: FAILED"
[ -f structures/alphafold/AF-P06787-F1-model_v4.cif ] || wget -q -O structures/alphafold/AF-P06787-F1-model_v4.cif "https://alphafold.ebi.ac.uk/files/AF-P06787-F1-model_v4.cif" && echo "  AF-P06787: OK" || echo "  AF-P06787: FAILED"
[ -f structures/alphafold/AF-P07339-F1-model_v4.cif ] || wget -q -O structures/alphafold/AF-P07339-F1-model_v4.cif "https://alphafold.ebi.ac.uk/files/AF-P07339-F1-model_v4.cif" && echo "  AF-P07339: OK" || echo "  AF-P07339: FAILED"
[ -f structures/alphafold/AF-P07858-F1-model_v4.cif ] || wget -q -O structures/alphafold/AF-P07858-F1-model_v4.cif "https://alphafold.ebi.ac.uk/files/AF-P07858-F1-model_v4.cif" && echo "  AF-P07858: OK" || echo "  AF-P07858: FAILED"
[ -f structures/alphafold/AF-P0DP23-F1-model_v4.cif ] || wget -q -O structures/alphafold/AF-P0DP23-F1-model_v4.cif "https://alphafold.ebi.ac.uk/files/AF-P0DP23-F1-model_v4.cif" && echo "  AF-P0DP23: OK" || echo "  AF-P0DP23: FAILED"
[ -f structures/alphafold/AF-P12931-F1-model_v4.cif ] || wget -q -O structures/alphafold/AF-P12931-F1-model_v4.cif "https://alphafold.ebi.ac.uk/files/AF-P12931-F1-model_v4.cif" && echo "  AF-P12931: OK" || echo "  AF-P12931: FAILED"
[ -f structures/alphafold/AF-P24941-F1-model_v4.cif ] || wget -q -O structures/alphafold/AF-P24941-F1-model_v4.cif "https://alphafold.ebi.ac.uk/files/AF-P24941-F1-model_v4.cif" && echo "  AF-P24941: OK" || echo "  AF-P24941: FAILED"
[ -f structures/alphafold/AF-P28482-F1-model_v4.cif ] || wget -q -O structures/alphafold/AF-P28482-F1-model_v4.cif "https://alphafold.ebi.ac.uk/files/AF-P28482-F1-model_v4.cif" && echo "  AF-P28482: OK" || echo "  AF-P28482: FAILED"
[ -f structures/alphafold/AF-P33176-F1-model_v4.cif ] || wget -q -O structures/alphafold/AF-P33176-F1-model_v4.cif "https://alphafold.ebi.ac.uk/files/AF-P33176-F1-model_v4.cif" && echo "  AF-P33176: OK" || echo "  AF-P33176: FAILED"
[ -f structures/alphafold/AF-P35579-F1-model_v4.cif ] || wget -q -O structures/alphafold/AF-P35579-F1-model_v4.cif "https://alphafold.ebi.ac.uk/files/AF-P35579-F1-model_v4.cif" && echo "  AF-P35579: OK" || echo "  AF-P35579: FAILED"
[ -f structures/alphafold/AF-P60709-F1-model_v4.cif ] || wget -q -O structures/alphafold/AF-P60709-F1-model_v4.cif "https://alphafold.ebi.ac.uk/files/AF-P60709-F1-model_v4.cif" && echo "  AF-P60709: OK" || echo "  AF-P60709: FAILED"
[ -f structures/alphafold/AF-P61626-F1-model_v4.cif ] || wget -q -O structures/alphafold/AF-P61626-F1-model_v4.cif "https://alphafold.ebi.ac.uk/files/AF-P61626-F1-model_v4.cif" && echo "  AF-P61626: OK" || echo "  AF-P61626: FAILED"
[ -f structures/alphafold/AF-P62158-F1-model_v4.cif ] || wget -q -O structures/alphafold/AF-P62158-F1-model_v4.cif "https://alphafold.ebi.ac.uk/files/AF-P62158-F1-model_v4.cif" && echo "  AF-P62158: OK" || echo "  AF-P62158: FAILED"
[ -f structures/alphafold/AF-P63098-F1-model_v4.cif ] || wget -q -O structures/alphafold/AF-P63098-F1-model_v4.cif "https://alphafold.ebi.ac.uk/files/AF-P63098-F1-model_v4.cif" && echo "  AF-P63098: OK" || echo "  AF-P63098: FAILED"
[ -f structures/alphafold/AF-P68871-F1-model_v4.cif ] || wget -q -O structures/alphafold/AF-P68871-F1-model_v4.cif "https://alphafold.ebi.ac.uk/files/AF-P68871-F1-model_v4.cif" && echo "  AF-P68871: OK" || echo "  AF-P68871: FAILED"
[ -f structures/alphafold/AF-P69905-F1-model_v4.cif ] || wget -q -O structures/alphafold/AF-P69905-F1-model_v4.cif "https://alphafold.ebi.ac.uk/files/AF-P69905-F1-model_v4.cif" && echo "  AF-P69905: OK" || echo "  AF-P69905: FAILED"
[ -f structures/alphafold/AF-P80946-F1-model_v4.cif ] || wget -q -O structures/alphafold/AF-P80946-F1-model_v4.cif "https://alphafold.ebi.ac.uk/files/AF-P80946-F1-model_v4.cif" && echo "  AF-P80946: OK" || echo "  AF-P80946: FAILED"
[ -f structures/alphafold/AF-Q16539-F1-model_v4.cif ] || wget -q -O structures/alphafold/AF-Q16539-F1-model_v4.cif "https://alphafold.ebi.ac.uk/files/AF-Q16539-F1-model_v4.cif" && echo "  AF-Q16539: OK" || echo "  AF-Q16539: FAILED"

echo 'Done!'
echo "Downloaded to structures/"